apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldbstorage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: manual
  hostPath:
    path: /mnt/data
    type: Directory
