apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldbstorage-pvc
  namespace: pskproject
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
